#!/bin/sh
exec 2>&1

# create group
if ! getent group pqconnect > /dev/null; then
  addgroup --quiet --system pqconnect
fi

# create user
if ! getent passwd pqconnect > /dev/null; then
  adduser --quiet --system --no-create-home --disabled-password --home /etc/pqconnect --ingroup pqconnect --gecos "pqconnect user" pqconnect
fi

# FORWARDING/NAT
/usr/share/rpiap/ifupdownd.link.d/50-iptables.sh pqccli0 up

# pqconnect - add prerouting hook (from dqcache to the client)
nft add table inet rpiap-pqconnect-filter
nft add chain inet rpiap-pqconnect-filter prerouting '{ type filter hook prerouting priority -10; policy accept; }'
nft add rule inet rpiap-pqconnect-filter prerouting udp sport 53 queue to 0

exec ./bin/pqconnect -a 10.75.0.1
