#!/bin/sh
exec 2>&1

if ! getent group rpiap > /dev/null; then
  addgroup --quiet --system rpiap
fi

if ! getent passwd rpiap > /dev/null; then
  adduser --quiet --system --no-create-home --disabled-password --home /var/lib/rpiap/env --ingroup rpiap --gecos "rpiap user" rpiap
fi

chown -R rpiap:rpiap /var/lib/rpiap/env

# binary
rm -rf ./bin
mkdir -p ./bin
cp /usr/bin/python3 ./bin/python3
setcap cap_net_admin,cap_sys_chroot+ep ./bin/python3

PATH="`pwd`/bin:$PATH"
export PATH
umask 077

# Change to www1 directory and run uvicorn as root
# XXX TODO: run under rpiap user/group
cd /usr/share/rpiap/www1
exec python3 -m uvicorn app:app --host 192.168.137.1 --port 80
