#!/bin/sh
exec 2>&1

if ! getent group rpiap > /dev/null; then
  addgroup --quiet --system rpiap
fi

if ! getent passwd rpiap > /dev/null; then
  adduser --quiet --system --no-create-home --disabled-password --home /var/lib/rpiap/env --ingroup rpiap --gecos "rpiap user" rpiap
fi

# create /var/run/rpiap/env
if [ ! -d /var/run/rpiap/env ]; then
  mkdir -p /var/run/rpiap/env
  cp /var/lib/rpiap/env/* /var/run/rpiap/env/
  chown -R rpiap:rpiap /var/run/rpiap/env
fi

chown -R rpiap:rpiap /var/lib/rpiap/env

# binary
rm -rf ./bin
mkdir -p ./bin
cp /usr/bin/python3 ./bin/python3
setcap cap_net_admin,cap_net_bind_service+ep ./bin/python3

PATH="`pwd`/bin:$PATH"
export PATH
umask 077

echo $PATH

# Change to www directory and run uvicorn under rpiap UID/GID
envuidgid rpiap sh -c '
 cd /usr/share/rpiap/www7
 exec /usr/share/rpiap/scripts/setuidgid.py python3 -m uvicorn app:app --host 192.168.137.1 --port 80
'
