#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# in preinst phase the directory doesn't exist
var='/var/lib/rpiap/env'
mkdir -p "${var}"

dbdo() {
  fn="$1"
  secret=$2
  dbname="rpiap/${fn}"

  # get value
  if [ -f "${var}/${fn}" ]; then
    db_set "${dbname}" "`cat ${var}/${fn}`"
  fi
  db_input critical "${dbname}" || true
  db_go

  # write value to env. directory
  db_get "${dbname}"
  (
    umask 077
    echo "${RET}" > "${var}/${fn}"
  )

  # clear value from the debconf DB
  if [ x"${secret}" != x ]; then
    db_set "${dbname}" "${secret}"
  fi
}

dbdo wlanssid
dbdo wlanpass _
dbdo wlanchannel
dbdo wlancountry
dbdo dhcpdns
dbdo restart

exit 0
