#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

if [ x"$1" = "xconfigure" ]; then

  if ! getent group rpiap > /dev/null; then
    addgroup --quiet --system rpiap
  fi

  if ! getent passwd rpiap > /dev/null; then
    adduser --quiet --system --no-create-home --disabled-password --home /var/lib/rpiap/env --ingroup rpiap --gecos "rpiap user" rpiap
  fi

  chown rpiap:rpiap /var/lib/rpiap/env
  chown rpiap:rpiap /var/lib/rpiap/env/* 2>/dev/null || :

  for d in `ls -1 /var/lib/rpiap/service`; do
    if [ ! -e "/etc/service/rpiap_${d}" ]; then
      echo -n "linking: /var/lib/rpiap/service/${d} -> /etc/service/rpiap_${d}"
      ln -s "/var/lib/rpiap/service/${d}" "/etc/service/rpiap_${d}"
      echo '. done.'
    fi
  done
fi

# leave only /etc/network/interfaces.d/rpiap
# XXX TODO: backup files and restore it in postrm
ls /etc/network/interfaces.d/ | while read name; do
  if [ x"${name}" = xrpiap ]; then
    continue
  fi
  echo "warning: /etc/network/interfaces.d/${name} removed" >&2
  rm "/etc/network/interfaces.d/${name}"
done

#DEBHELPER#
