#!/bin/sh
exec 2>&1

# wait for loopback interface to be available
while true; do
  link="`cat /sys/class/net/lo/operstate 2>/dev/null || true`"
  if [ x"${link}" != xdown ]; then
    break
  fi
  sleep 1
done

# check interface configuration
for interface in wlan1 eth0 eth1 eth2 usb0; do
  all="`ifquery -v ${interface} 2>&1 | grep  '^ifquery: querying interface'`"
  rpiap="`ifquery -vi /etc/network/interfaces.d/rpiap ${interface} 2>&1 | grep  '^ifquery: querying interface'`"
  if [ x"${all}" != x"${rpiap}" ]; then
    echo "warning: ${interface} configured outside /etc/network/interfaces.d/rpiap !!!!"
    sleep 60
    exit 1
  fi
done

exec /usr/share/rpiap/scripts/ifupdownd.py -i wlan0 -i eth0 -i wlan1 -i eth1 -i eth2 -i usb0 -l /usr/share/rpiap/ifupdownd.link.d -d /usr/share/rpiap/ifupdownd.device.d
