#!/bin/sh
exec 2>&1

# wait for loopback interface to be available
while true; do
  link="`cat /sys/class/net/lo/operstate 2>/dev/null || true`"
  if [ x"${link}" != xdown ]; then
    break
  fi
  sleep 1
done

# check interface configuration
for interface in wlan1 eth0 eth1 eth2 usb0; do
  all="`ifquery -v ${interface} 2>&1 | grep  '^ifquery: querying interface'`"
  rpiap="`ifquery -vi /etc/network/interfaces.d/rpiap ${interface} 2>&1 | grep  '^ifquery: querying interface'`"
  if [ x"${all}" != x"${rpiap}" ]; then
    echo "warning: ${interface} configured outside /etc/network/interfaces.d/rpiap !!!!"
    sleep 60
    exit 1
  fi
done

lan='lan'

# run iptables NAT rules
for interface in wlan1 eth0 eth1 eth2 usb0 pqccli0; do
  iptables -t nat -A POSTROUTING -o "${interface}" -j MASQUERADE
  iptables -A FORWARD -i "${interface}" -o "${lan}" -m state --state RELATED,ESTABLISHED -j ACCEPT
  iptables -A FORWARD -i "${lan}" -o "${interface}" -j ACCEPT

  ip6tables -t nat -A POSTROUTING -o "${interface}" -j MASQUERADE
  ip6tables -A FORWARD -i "${interface}" -o "${lan}" -m state --state RELATED,ESTABLISHED -j ACCEPT
  ip6tables -A FORWARD -i "${lan}" -o "${interface}" -j ACCEPT
done

exec /usr/share/rpiap/scripts/ifupdownd.py -i wlan0 -i eth0 -i wlan1 -i eth1 -i eth2 -i usb0 -l /usr/share/rpiap/scripts/ifupdownd-dhcp.sh -d /usr/share/rpiap/scripts/ifupdownd-updown.sh
